name: Docker Image CI

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    branches:
      - master
    tags:
      - '*'

jobs:

  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-latest]
        arch: [arm64]

    steps:
    - uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker
      uses: docker/login-action@v1
      # 配置登录信息，secrets 变量在 github settings -> secrets 中设置
      with:
        # registry: ${{ secrets.ALI_DOCKER_HUB_REGISTRY }}
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_PWD }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: weiweicool/fanqie-novel-download-on-web
    
    - name: Build and push stream-park
      uses: docker/build-push-action@v3
      with:
        context: .
        file: Dockerfile
        platforms: linux/amd64,linux/arm64/v8
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
    
    - name: Login to Ali Docker
      uses: docker/login-action@v1
      # 配置登录信息，secrets 变量在 github settings -> secrets 中设置
      with:
        registry: registry.cn-chengdu.aliyuncs.com
        username: ${{ secrets.Ali_USER }}
        password: ${{ secrets.Ali_PWD }}

    - name: Extract metadata (tags, labels) for Ali Docker
      id: meta_a
      uses: docker/metadata-action@v4
      with:
        images: registry.cn-chengdu.aliyuncs.com/weiweicool-mine/weiwei-self

    - name: Push Docker image to Aliyun Container Registry
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        platforms: linux/amd64,linux/arm64/v8
        tags: ${{ steps.meta_a.outputs.tags }}
        labels: ${{ steps.meta_a.outputs.labels }}
