name: Docker Image CI

on:
  push:
    tags:
      - '*'
  pull_request:
    tags:
      - '*'

jobs:

  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-latest]
        arch: [arm64]

    steps:
    - uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker
      uses: docker/login-action@v1
      # 配置登录信息，secrets 变量在 github settings -> secrets 中设置
      with:
        # registry: ${{ secrets.ALI_DOCKER_HUB_REGISTRY }}
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_PWD }}

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: weiweicool/fanqie-novel-download-on-web
        tags: |
          type=raw,value=latest,enable={{is_default_branch}}
          type=ref,event=tag
          type=ref,event=branch
    
    - name: Build and push streampark
      uses: docker/build-push-action@v3
      with:
        context: .
        file: Dockerfile
        platforms: linux/amd64,linux/arm64/v8
        push: true
        tags: weiweicool/fanqie-novel-download-on-web:${{ github.ref }}
        labels: weiweicool/fanqie-novel-download-on-web:${{ github.ref }}
    
    - name: Login to Ali Docker
      uses: docker/login-action@v1
      # 配置登录信息，secrets 变量在 github settings -> secrets 中设置
      with:
        registry: registry.cn-chengdu.aliyuncs.com
        username: ${{ secrets.Ali_USER }}
        password: ${{ secrets.Ali_PWD }}
    - name: Push Docker image to Aliyun Container Registry
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        platforms: linux/amd64,linux/arm64/v8
        tags: registry.cn-chengdu.aliyuncs.com/weiweicool-mine/weiwei-self:latest,registry.cn-chengdu.aliyuncs.com/weiweicool-mine/weiwei-self:${{ github.ref }}
