name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-latest]
        arch: [arm64]

    steps:
    - uses: actions/checkout@v3
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag fanqie-novel-download-on-web:$(date +%s) --tag my-image-name:latest

    - name: Login to Ali Docker
      uses: docker/login-action@v1
      # 配置登录信息，secrets 变量在 github settings -> secrets 中设置
      with:
        # registry: ${{ secrets.ALI_DOCKER_HUB_REGISTRY }}
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_PWD }}
    
    - name: Push Docker image to a container registry
      run:
        docker push fanqie-novel-download-on-web:latest
