name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-latest]
        arch: [arm64]

    steps:
    - uses: actions/checkout@v3

    - name: Get Git tag
      id: git-tag
      run: echo ::set-output name=tag::$(git describe --tags --abbrev=0)
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag fanqie-novel-download-on-web:$(date +%s) --tag fanqie-novel-download-on-web:${{ steps.git-tag.outputs.tag }}

    - name: Log in to Docker Hub with Token
      run: docker login -u ${{ secrets.DOCKERHUB_USER }} -p ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Push Docker image to a container registry
      run:
        docker push fanqie-novel-download-on-web:latest
